<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Hora est. Sudamérica Pacífico">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="HP-PC"><DocLocation><![CDATA[C:\casos\Emision Interact_ V00\ATC_00030_Emision_Issue]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ATC_00030_Emision_Issue]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[ATC_Genera_Carpeta_Evidencias_Issue [ATC_Genera_Carpetas_Evidencias]]]></AName>
<Summary sTime="12/01/2017 - 15:32:15" eTime="12/01/2017 - 15:32:17" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[ATC_Genera_Carpeta_Evidencias_Issue [ATC_Genera_Carpetas_Evidencias] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:17]]></Time>
<TimeTick>1484245937</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:17]]></Time>
<TimeTick>1484245937</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="0" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[Iniciar sesión.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión / Cerrar]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="23" >
<Disp><![CDATA[Iniciar sesión.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="23" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="23" >
<Disp><![CDATA[Iniciar sesión / Cerrar]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[NumeroDeAgente.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:19]]></Time>
<TimeTick>1484245939</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="24" >
<Disp><![CDATA[NumeroDeAgente.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[NumeroDeAgente.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["991501"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:20]]></Time>
<TimeTick>1484245940</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="26" >
<Disp><![CDATA[NumeroDeAgente.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Contrasena.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:20]]></Time>
<TimeTick>1484245940</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="28" >
<Disp><![CDATA[Contrasena.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Contrasena.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["inter20"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:22]]></Time>
<TimeTick>1484245942</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="30" >
<Disp><![CDATA[Contrasena.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[CodigoDeAerolinea.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:22]]></Time>
<TimeTick>1484245942</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="32" >
<Disp><![CDATA[CodigoDeAerolinea.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[CodigoDeAerolinea.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["LA"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:23]]></Time>
<TimeTick>1484245943</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="34" >
<Disp><![CDATA[CodigoDeAerolinea.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[DutyCode.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:23]]></Time>
<TimeTick>1484245943</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="36" >
<Disp><![CDATA[DutyCode.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[DutyCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:24]]></Time>
<TimeTick>1484245944</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="38" >
<Disp><![CDATA[DutyCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[LoginOK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:27]]></Time>
<TimeTick>1484245947</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="42" >
<Disp><![CDATA[LoginOK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="20" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="24" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:30]]></Time>
<TimeTick>1484245950</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:30]]></Time>
<TimeTick>1484245950</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="46" >
<Disp><![CDATA[PopUp OK.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="40" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="46" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="0" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Login Ok]]></Obj>
<Details ><![CDATA[Usuario ingresado: 991501]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:31]]></Time>
<TimeTick>1484245951</TimeTick>
<NodeArgs eType="User" icon="10" nRep="42" status="Passed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="58" >
<Disp><![CDATA[Login Ok]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Interact-v7.10-CVT-08Nov16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:31]]></Time>
<TimeTick>1484245951</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:31]]></Time>
<TimeTick>1484245951</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Version Control(st).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:31]]></Time>
<TimeTick>1484245951</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="47" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="66" >
<Disp><![CDATA[Version Control(st).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="66" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="45" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="66" >
<Disp><![CDATA[Interact-v7.10-CVT-08Nov16]]></Disp>
</NodeArgs>
</Step>
<Action rID="T29">
<AName><![CDATA[ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:49]]></Time>
<TimeTick>1484245969</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicAltDwn&gt&lt__MicF3&gt&lt__MicAltUp&gt"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:49]]></Time>
<TimeTick>1484245969</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="689" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="688" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-07Aug16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:49]]></Time>
<TimeTick>1484245969</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Configuración de la aplicación]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:49]]></Time>
<TimeTick>1484245969</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Cambiar Ciudad.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:49]]></Time>
<TimeTick>1484245969</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="693" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="3" >
<Disp><![CDATA[Cambiar Ciudad.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Detalle OAC:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:50]]></Time>
<TimeTick>1484245970</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="694" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="5" >
<Disp><![CDATA[Detalle OAC:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Detalle OAC:.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:50]]></Time>
<TimeTick>1484245970</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="696" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="7" >
<Disp><![CDATA[Detalle OAC:.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="692" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="3" >
<Disp><![CDATA[Configuración de la aplicación]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="691" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="3" >
<Disp><![CDATA[Interact-v7.3-07Aug16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:50]]></Time>
<TimeTick>1484245970</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[OAC Ciudad AAA]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:50]]></Time>
<TimeTick>1484245970</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[CiudadDeseada.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:50]]></Time>
<TimeTick>1484245970</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="700" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="11" >
<Disp><![CDATA[CiudadDeseada.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[CiudadDeseada.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["REV"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:50]]></Time>
<TimeTick>1484245970</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="702" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="12" >
<Disp><![CDATA[CiudadDeseada.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[CodigoOficina.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:52]]></Time>
<TimeTick>1484245972</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="704" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="18" >
<Disp><![CDATA[CodigoOficina.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[CodigoOficina.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["REV"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:52]]></Time>
<TimeTick>1484245972</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="706" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="19" >
<Disp><![CDATA[CodigoOficina.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[CodigoDeCuenta.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:53]]></Time>
<TimeTick>1484245973</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="708" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="26" >
<Disp><![CDATA[CodigoDeCuenta.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[CodigoDeCuenta.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["CP"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:53]]></Time>
<TimeTick>1484245973</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="710" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="27" >
<Disp><![CDATA[CodigoDeCuenta.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[CodigoOficina2.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:54]]></Time>
<TimeTick>1484245974</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="712" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="37" >
<Disp><![CDATA[CodigoOficina2.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[CodigoOficina2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["76999204"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:54]]></Time>
<TimeTick>1484245974</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="714" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="38" >
<Disp><![CDATA[CodigoOficina2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:55]]></Time>
<TimeTick>1484245975</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="716" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="52" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="699" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="11" >
<Disp><![CDATA[OAC Ciudad AAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Configuración de la aplicación]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:56]]></Time>
<TimeTick>1484245976</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Boton OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/01/2017 - 15:32:56]]></Time>
<TimeTick>1484245976</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="719" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="56" >
<Disp><![CDATA[Boton OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="718" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="56" >
<Disp><![CDATA[Configuración de la aplicación]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="698" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="11" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/01/2017 - 15:32:49" eTime="12/01/2017 - 15:32:59" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="686" >
<Disp><![CDATA[ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T50">
<AName><![CDATA[ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Interact-v7.8-CVT-04Oct16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:19]]></Time>
<TimeTick>1484245999</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[NonModalPopupPresImpl$NonModal]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:19]]></Time>
<TimeTick>1484245999</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[PrinterIcon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:19]]></Time>
<TimeTick>1484245999</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="725" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="4" >
<Disp><![CDATA[PrinterIcon.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="724" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="4" >
<Disp><![CDATA[NonModalPopupPresImpl$NonModal]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="723" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="4" >
<Disp><![CDATA[Interact-v7.8-CVT-04Oct16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:19]]></Time>
<TimeTick>1484245999</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicCtrlDwn&gtp&lt__MicCtrlUp&gt"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:19]]></Time>
<TimeTick>1484245999</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="728" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="12" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="727" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="12" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-07Aug16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:20]]></Time>
<TimeTick>1484246000</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Funciones de la impresora]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:20]]></Time>
<TimeTick>1484246000</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Seleccionar :.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Asignar las impresoras"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:20]]></Time>
<TimeTick>1484246000</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="732" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="14" >
<Disp><![CDATA[Seleccionar :.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Impresora de Boletos.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["OFF"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:21]]></Time>
<TimeTick>1484246001</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="734" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="17" >
<Disp><![CDATA[Impresora de Boletos.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Impresora de Boletos.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:22]]></Time>
<TimeTick>1484246002</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="736" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="19" >
<Disp><![CDATA[Impresora de Boletos.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[TipoDeRutina.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:22]]></Time>
<TimeTick>1484246002</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="738" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[TipoDeRutina.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Impresora de Boletos.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["OFF"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:22]]></Time>
<TimeTick>1484246002</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="740" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="17" >
<Disp><![CDATA[Impresora de Boletos.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Impresora de Boletos.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:23]]></Time>
<TimeTick>1484246003</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="742" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="19" >
<Disp><![CDATA[Impresora de Boletos.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[TipoDeRutina.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:23]]></Time>
<TimeTick>1484246003</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="743" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[TipoDeRutina.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[ImpresoraDeBoletos.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/01/2017 - 15:33:24]]></Time>
<TimeTick>1484246004</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="745" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="25" >