<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Hora est. Sudamérica Pacífico">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="HP-PC"><DocLocation><![CDATA[C:\casos\Emision Interact_ V00\ATC_00030_Emision_Issue]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ATC_00030_Emision_Issue]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[ATC_Genera_Carpeta_Evidencias_Issue [ATC_Genera_Carpetas_Evidencias]]]></AName>
<Summary sTime="17/01/2017 - 18:47:45" eTime="17/01/2017 - 18:47:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[ATC_Genera_Carpeta_Evidencias_Issue [ATC_Genera_Carpetas_Evidencias] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:47]]></Time>
<TimeTick>1484689667</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:47]]></Time>
<TimeTick>1484689667</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="0" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:47]]></Time>
<TimeTick>1484689667</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run "C:\Sabre Interact\Res\v7.10PreRelease\app\QikDesktop.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Sabre Interact\Res\v7.10PreRelease\app\QikDesktop.exe",1]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:47]]></Time>
<TimeTick>1484689667</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[Run "C:\Sabre Interact\Res\v7.10PreRelease\app\QikDesktop.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="15" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="0" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Argumento o llamada a procedimiento no válidos<BR>Line (2): &quot;SystemUtil.Run &quot;C:\Sabre Interact\Res\v7.10PreRelease\app\QikDesktop.exe&quot;&quot;. ]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:47]]></Time>
<TimeTick>1484689667</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[PopupDialog.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="5" >
<Disp><![CDATA[PopupDialog.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="5" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Contrasena.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="8" >
<Disp><![CDATA[Contrasena.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[Iniciar sesión.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="87" >
<Disp><![CDATA[Iniciar sesión.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicAltDwn&gtmicF3&lt__MicAltUp&gt"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="89" >
<Disp><![CDATA[Iniciar sesión.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="22" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="8" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Configuración de la aplicación]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Cambiar a CERT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:56]]></Time>
<TimeTick>1484689676</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="93" >
<Disp><![CDATA[Cambiar a CERT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Cambiar a CERT.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:57]]></Time>
<TimeTick>1484689677</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="98" >
<Disp><![CDATA[Cambiar a CERT.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Boton OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:47:57]]></Time>
<TimeTick>1484689677</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="34" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="105" >
<Disp><![CDATA[Boton OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Boton OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:00]]></Time>
<TimeTick>1484689680</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="37" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="107" >
<Disp><![CDATA[Boton OK.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="29" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="93" >
<Disp><![CDATA[Configuración de la aplicación]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:02]]></Time>
<TimeTick>1484689682</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:02]]></Time>
<TimeTick>1484689682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="39" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="114" >
<Disp><![CDATA[PopUp OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:02]]></Time>
<TimeTick>1484689682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="41" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="115" >
<Disp><![CDATA[PopUp OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="38" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="114" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:02]]></Time>
<TimeTick>1484689682</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[NumeroDeAgente.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:02]]></Time>
<TimeTick>1484689682</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="121" >
<Disp><![CDATA[NumeroDeAgente.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[NumeroDeAgente.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["40015"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:03]]></Time>
<TimeTick>1484689683</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="123" >
<Disp><![CDATA[NumeroDeAgente.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Contrasena.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:03]]></Time>
<TimeTick>1484689683</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="125" >
<Disp><![CDATA[Contrasena.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Contrasena.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["canales4"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:04]]></Time>
<TimeTick>1484689684</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="127" >
<Disp><![CDATA[Contrasena.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[CodigoDeAerolinea.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:04]]></Time>
<TimeTick>1484689684</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="129" >
<Disp><![CDATA[CodigoDeAerolinea.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[CodigoDeAerolinea.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["LA"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:05]]></Time>
<TimeTick>1484689685</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="131" >
<Disp><![CDATA[CodigoDeAerolinea.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[DutyCode.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:05]]></Time>
<TimeTick>1484689685</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="133" >
<Disp><![CDATA[DutyCode.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[DutyCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:06]]></Time>
<TimeTick>1484689686</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="135" >
<Disp><![CDATA[DutyCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[LoginOK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:08]]></Time>
<TimeTick>1484689688</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="60" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="139" >
<Disp><![CDATA[LoginOK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="43" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="121" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:09]]></Time>
<TimeTick>1484689689</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:09]]></Time>
<TimeTick>1484689689</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="62" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="143" >
<Disp><![CDATA[PopUp OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:10]]></Time>
<TimeTick>1484689690</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="147" >
<Disp><![CDATA[PopUp OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="61" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="143" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="19" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="5" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[Login error]]></Obj>
<Details ><![CDATA[Número de agente o contraseña no válidos.]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:10]]></Time>
<TimeTick>1484689690</TimeTick>
<NodeArgs eType="User" icon="12" nRep="65" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="148" >
<Disp><![CDATA[Login error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The set DataTable.Value operation failed. The &lt;ErrorOUT&gt; column does not exist.<BR>Line (150): &quot;DataTable(&quot;ErrorOUT&quot;, dtGlobalSheet) = MensajePopUp&quot;. ]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:10]]></Time>
<TimeTick>1484689690</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="149" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The set DataTable.Value operation failed. The &lt;ErrorOUT&gt; column does not exist.<BR>Line (150): &quot;DataTable(&quot;ErrorOUT&quot;, dtGlobalSheet) = MensajePopUp&quot;. ]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:42]]></Time>
<TimeTick>1484689722</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="149" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The set DataTable.Value operation failed. The &lt;ErrorOUT&gt; column does not exist.<BR>Line (150): &quot;DataTable(&quot;ErrorOUT&quot;, dtGlobalSheet) = MensajePopUp&quot;. ]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:44]]></Time>
<TimeTick>1484689724</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="68" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="149" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The set DataTable.Value operation failed. The &lt;ErrorOUT&gt; column does not exist.<BR>Line (150): &quot;DataTable(&quot;ErrorOUT&quot;, dtGlobalSheet) = MensajePopUp&quot;. ]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:49]]></Time>
<TimeTick>1484689729</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" status="Failed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="149" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[17/01/2017 - 18:48:58]]></Time>
<TimeTick>1484689738</TimeTick>
<NodeArgs eType="General" icon="13" nRep="70" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="17/01/2017 - 18:47:47" eTime="17/01/2017 - 18:48:58" passed="0" failed="7" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="9" status="Failed" >
<Disp><![CDATA[ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact] Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[ATC_00030_Emision_Issue Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="17/01/2017 - 18:47:43" eTime="17/01/2017 - 18:48:58" passed="0" failed="7" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test ATC_00030_Emision_Issue Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>