<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Hora est. Sudamérica Pacífico">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="HP-PC"><DocLocation><![CDATA[C:\casos\Emision Interact_ V00\ATC_00030_Emision_Issue]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ATC_00030_Emision_Issue]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[ATC_Genera_Carpeta_Evidencias_Issue [ATC_Genera_Carpetas_Evidencias]]]></AName>
<Summary sTime="17/01/2017 - 18:51:09" eTime="17/01/2017 - 18:51:11" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[ATC_Genera_Carpeta_Evidencias_Issue [ATC_Genera_Carpetas_Evidencias] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="0" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[Iniciar sesión.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="87" >
<Disp><![CDATA[Iniciar sesión.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicAltDwn&gtmicF3&lt__MicAltUp&gt"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="89" >
<Disp><![CDATA[Iniciar sesión.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="20" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Configuración de la aplicación]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Cambiar a CERT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:11]]></Time>
<TimeTick>1484689871</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="93" >
<Disp><![CDATA[Cambiar a CERT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Cambiar a CERT.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:12]]></Time>
<TimeTick>1484689872</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="98" >
<Disp><![CDATA[Cambiar a CERT.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Boton OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:12]]></Time>
<TimeTick>1484689872</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="105" >
<Disp><![CDATA[Boton OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Boton OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:15]]></Time>
<TimeTick>1484689875</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="107" >
<Disp><![CDATA[Boton OK.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="93" >
<Disp><![CDATA[Configuración de la aplicación]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:17]]></Time>
<TimeTick>1484689877</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:17]]></Time>
<TimeTick>1484689877</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="114" >
<Disp><![CDATA[PopUp OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:17]]></Time>
<TimeTick>1484689877</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="115" >
<Disp><![CDATA[PopUp OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="27" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="114" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Iniciar sesión]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:17]]></Time>
<TimeTick>1484689877</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[NumeroDeAgente.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:17]]></Time>
<TimeTick>1484689877</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="33" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="121" >
<Disp><![CDATA[NumeroDeAgente.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[NumeroDeAgente.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["40015"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:18]]></Time>
<TimeTick>1484689878</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="123" >
<Disp><![CDATA[NumeroDeAgente.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Contrasena.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:18]]></Time>
<TimeTick>1484689878</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="125" >
<Disp><![CDATA[Contrasena.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Contrasena.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["canales1"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:19]]></Time>
<TimeTick>1484689879</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="127" >
<Disp><![CDATA[Contrasena.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[CodigoDeAerolinea.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:19]]></Time>
<TimeTick>1484689879</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="129" >
<Disp><![CDATA[CodigoDeAerolinea.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[CodigoDeAerolinea.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["LA"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:20]]></Time>
<TimeTick>1484689880</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="131" >
<Disp><![CDATA[CodigoDeAerolinea.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[DutyCode.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:20]]></Time>
<TimeTick>1484689880</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="133" >
<Disp><![CDATA[DutyCode.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[DutyCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:21]]></Time>
<TimeTick>1484689881</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="135" >
<Disp><![CDATA[DutyCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[LoginOK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:23]]></Time>
<TimeTick>1484689883</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="139" >
<Disp><![CDATA[LoginOK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="121" >
<Disp><![CDATA[Iniciar sesión]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:30]]></Time>
<TimeTick>1484689890</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[PopUp OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:30]]></Time>
<TimeTick>1484689890</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="143" >
<Disp><![CDATA[PopUp OK.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="52" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="143" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="0" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[Login Ok]]></Obj>
<Details ><![CDATA[Usuario ingresado: 40015]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:30]]></Time>
<TimeTick>1484689890</TimeTick>
<NodeArgs eType="User" icon="10" nRep="54" status="Passed" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="155" >
<Disp><![CDATA[Login Ok]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf3.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Interact-v7.10-CVT-08Nov16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:35]]></Time>
<TimeTick>1484689895</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[PopupDialog]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:35]]></Time>
<TimeTick>1484689895</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Version Control(st).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:35]]></Time>
<TimeTick>1484689895</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="59" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="163" >
<Disp><![CDATA[Version Control(st).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="163" >
<Disp><![CDATA[PopupDialog]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="57" Source="ATC_Login_Printer_Sabre_Interact [ATC_Login_Interact]" SourceLine="163" >
<Disp><![CDATA[Interact-v7.10-CVT-08Nov16]]></Disp>
</NodeArgs>
</Step>
<Action rID="T36">
<AName><![CDATA[ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:47]]></Time>
<TimeTick>1484689907</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicAltDwn&gt&lt__MicF3&gt&lt__MicAltUp&gt"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:47]]></Time>
<TimeTick>1484689907</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="461" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="460" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="1" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-07Aug16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:47]]></Time>
<TimeTick>1484689907</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Configuración de la aplicación]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:47]]></Time>
<TimeTick>1484689907</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Cambiar Ciudad.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:47]]></Time>
<TimeTick>1484689907</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="465" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="3" >
<Disp><![CDATA[Cambiar Ciudad.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Detalle OAC:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:48]]></Time>
<TimeTick>1484689908</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="466" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="5" >
<Disp><![CDATA[Detalle OAC:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Detalle OAC:.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:49]]></Time>
<TimeTick>1484689909</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="468" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="7" >
<Disp><![CDATA[Detalle OAC:.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="464" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="3" >
<Disp><![CDATA[Configuración de la aplicación]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="463" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="3" >
<Disp><![CDATA[Interact-v7.3-07Aug16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:49]]></Time>
<TimeTick>1484689909</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[OAC Ciudad AAA]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:49]]></Time>
<TimeTick>1484689909</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[CiudadDeseada.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:49]]></Time>
<TimeTick>1484689909</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="472" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="11" >
<Disp><![CDATA[CiudadDeseada.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[CiudadDeseada.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TCQ"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:49]]></Time>
<TimeTick>1484689909</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="474" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="12" >
<Disp><![CDATA[CiudadDeseada.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[CodigoOficina.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:50]]></Time>
<TimeTick>1484689910</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="476" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="18" >
<Disp><![CDATA[CodigoOficina.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[CodigoOficina.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TCQ"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:50]]></Time>
<TimeTick>1484689910</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="478" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="19" >
<Disp><![CDATA[CodigoOficina.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[CodigoDeCuenta.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:51]]></Time>
<TimeTick>1484689911</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="480" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="26" >
<Disp><![CDATA[CodigoDeCuenta.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[CodigoDeCuenta.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["P1"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:51]]></Time>
<TimeTick>1484689911</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="482" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="27" >
<Disp><![CDATA[CodigoDeCuenta.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[CodigoOficina2.SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:52]]></Time>
<TimeTick>1484689912</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="484" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="37" >
<Disp><![CDATA[CodigoOficina2.SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[CodigoOficina2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["91991185"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:52]]></Time>
<TimeTick>1484689912</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="486" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="38" >
<Disp><![CDATA[CodigoOficina2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:54]]></Time>
<TimeTick>1484689914</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="488" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="52" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="471" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="11" >
<Disp><![CDATA[OAC Ciudad AAA]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Configuración de la aplicación]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:55]]></Time>
<TimeTick>1484689915</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Boton OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[17/01/2017 - 18:51:55]]></Time>
<TimeTick>1484689915</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="491" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="56" >
<Disp><![CDATA[Boton OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="490" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="56" >
<Disp><![CDATA[Configuración de la aplicación]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="470" Source="ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact]" SourceLine="11" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="17/01/2017 - 18:51:47" eTime="17/01/2017 - 18:51:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="458" >
<Disp><![CDATA[ATC_OAC_AAA_Sabre_Interact [ATC_Login_Interact] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T57">
<AName><![CDATA[ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]]]></AName>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Interact-v7.8-CVT-04Oct16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:17]]></Time>
<TimeTick>1484689937</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[NonModalPopupPresImpl$NonModal]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:17]]></Time>
<TimeTick>1484689937</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[PrinterIcon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:17]]></Time>
<TimeTick>1484689937</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="497" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="4" >
<Disp><![CDATA[PrinterIcon.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="496" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="4" >
<Disp><![CDATA[NonModalPopupPresImpl$NonModal]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="495" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="4" >
<Disp><![CDATA[Interact-v7.8-CVT-04Oct16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:17]]></Time>
<TimeTick>1484689937</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicCtrlDwn&gtp&lt__MicCtrlUp&gt"]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:17]]></Time>
<TimeTick>1484689937</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="500" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="12" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="499" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="12" >
<Disp><![CDATA[Interact-v7.3-CVT-05Jul16]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Interact-v7.3-07Aug16]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:18]]></Time>
<TimeTick>1484689938</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Funciones de la impresora]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:18]]></Time>
<TimeTick>1484689938</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Seleccionar :.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Asignar las impresoras"]]></Details>
<Time><![CDATA[17/01/2017 - 18:52:18]]></Time>
<TimeTick>1484689938</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="504" Source="ATC_Configuracion_Impresora_Sabre_Interact [ATC_Login_Interact]" SourceLine="14" >
<Disp><![CDATA[Seleccionar :.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">